### ISSUE TITLE
Banning someone doesn't ban then

### ISSUE THREAD

**Issue by rubenwardy** [shivajiva101/sban#2]
I first banned a player, and it kicked them from a game:

> CTF_Bot, ban PotatoGuy cheating
> <CTF_Bot> *** PotatoGuy left the game

However they then appeared back ingame later on, and banning had no response

> CTF_Bot, ban PotatoGuy cheating

So I had to kick them.

I'm also using the irc mod and sauth.

> secure.trusted_mods = sban,irc,sauth

Here is the ban record:

> <CTF_Bot> Player records: 1
> <CTF_Bot> [1] Name: PotatoGuy IP: <<IP>> Created: Sun 08 Oct 2017 07:19:29 PM UTC Last login: Mon 09 Oct 2017 12:21:55 AM UTC
> <CTF_Bot> Ban records: 1
> <CTF_Bot> [1] Name: PotatoGuy Created: Sun 08 Oct 2017 07:23:07 PM UTC Banned by: user Reason: cheating Expires: Sun 08 Oct 2017 07:23:07 PM UTC
> <CTF_Bot> [1] Unbanned by: sban Reason: ban expired Time: Mon 09 Oct 2017 12:21:53 AM UTC
> <CTF_Bot> Banned: false

---------

```
2017-10-08 19:23:07: ACTION[Server]: [sban] PotatoGuy temp banned by user reason: cheating
2017-10-09 00:21:53: ACTION[Server]: [sban] PotatoGuy unbanned by sban reason: ban expired
/home/minetest/.minetest/mods/sban/init.lua:44: attempt to index local 't' (a number value)
	/home/minetest/.minetest/mods/sban/init.lua:44: in function 'parse_time'
	/home/minetest/.minetest/mods/sban/init.lua:775: in function 'func'
/home/minetest/.minetest/mods/sban/init.lua:44: attempt to index local 't' (a number value)
	/home/minetest/.minetest/mods/sban/init.lua:44: in function 'parse_time'
	/home/minetest/.minetest/mods/sban/init.lua:775: in function 'func'
```

**Comment by rubenwardy** [comment]
It would also be good to show "indefinite" or some synonym on a permanent ban

**Comment by shivajiva101** [comment]
check for zero added to prevent ban expiring immediately.
When working properly the record states Expires: Never
