### ISSUE TITLE
Performance improvements by creating indexes and primary keys on sban tables (upgrade script attached)

### ISSUE THREAD

**Issue by jhooper04** [shivajiva101/sban#25]
Wrote an upgrade script to create indexes on name and ip fields as well as adding some primary keys for the id columns that didn't have them. This should greatly improve performance as the database size grows.

Attached is the upgrade script file saved as .txt, github didn't like the .sql file for some reason.
shouldn't need to change any queries, just run the script on the db.

I didn't get to try this upgrade script with real data, it should work, but if there are any primary key conflicts during upgrading it should rollback the transaction. in the case of conflicts, i considered adding "PRIMARY KEY ON CONFLICT IGNORE" or "PRIMARY KEY ON CONFLICT REPLACE" but im not sure which would be more appropriate. 

[sban_upgrade_indexes.txt](https://github.com/shivajiva101/sban/files/3544130/sban_upgrade_indexes.txt)

**Comment by jhooper04** [comment]
This shows how the query plan uses the new indexes and primary keys to verify that it will increase performance:

EXPLAIN QUERY PLAN
SELECT players.id
FROM players
INNER JOIN playerdata ON playerdata.id = players.id
WHERE playerdata.ip = '192.168.1.1' LIMIT 1;


selectid order from
"0"	"0"	"1"	"SEARCH TABLE playerdata USING COVERING INDEX idx_playerdata_ip (ip=?)"
"0"	"1"	"0"	"SEARCH TABLE players USING INTEGER PRIMARY KEY (rowid=?)"





EXPLAIN QUERY PLAN
SELECT players.id
FROM players
INNER JOIN playerdata ON playerdata.id = players.id
WHERE playerdata.name = 'jSnake' LIMIT 1;


selectid order from
"0"	"0"	"1"	"SEARCH TABLE playerdata USING COVERING INDEX idx_playerdata_name (name=?)"
"0"	"1"	"0"	"SEARCH TABLE players USING INTEGER PRIMARY KEY (rowid=?)"

------------------------- this is the before -------------------------------------------

EXPLAIN QUERY PLAN
SELECT players.id
FROM players
INNER JOIN playerdata ON playerdata.id = players.id
WHERE playerdata.ip = '192.168.1.1' LIMIT 1;

"0"	"0"	"1"	"SCAN TABLE playerdata"
"0"	"1"	"0"	"SEARCH TABLE players USING INTEGER PRIMARY KEY (rowid=?)"

**Comment by rubenwardy** [comment]
when applying I get this:

Error: near line 41: UNIQUE constraint failed: bans.id
Error: near line 42: UNIQUE constraint failed: playerdata.id

```
sqlite> SELECT id, COUNT(*) c FROM bans GROUP BY id HAVING c > 1;
60|3
144|2
701|2
758|2
816|3
945|2
1020|2
1026|2
1176|2
1405|2
1628|2
1690|2
1820|2
2052|2
2422|2
2790|2
2833|4
2901|2
2981|7
3013|3
3139|2
3603|5
3708|4
3752|2
3953|2
4121|3
4233|2
4374|3
4438|2
4573|3
4636|2
4743|2
4788|2
5134|2
5326|2
5521|2
5544|3
5560|2
6082|4
6381|2
6429|2
6550|2
7181|2
7756|2
7994|2
7998|2
8340|4
9043|8
9081|2
9165|2
10372|10
10434|3
10666|2
10717|2
10980|2
11224|2
11440|3
11779|2
13148|2
13187|2
13424|2
13577|2
13598|2
13800|3
14315|14
14772|2
15236|3
15426|2
15850|2
16493|3
16712|3
16851|3
17242|3
17421|2
17798|4
18687|2
18875|3
19600|3
19636|9
20111|3
20837|7
20854|2
23194|2
23991|2
25487|4
26070|3
26406|4
28743|2
29148|2
31544|4
31684|2
31813|2
33170|3
33675|3
33726|2
35975|3
36197|2
36333|2
36964|3
37272|2
37549|2
38177|2
38241|4
40028|2
42272|2
44213|2
45218|2
45313|3
46852|2
52868|4
53034|4
54612|2
54856|2
55036|2
55978|2
64157|8
71490|3
72668|3
74192|2
79639|2
79901|4
82480|4
82570|3
83014|2
84769|2
86450|2
88900|3
96638|2
105257|2
106317|2
107724|4
107763|2
109384|2
110043|4
111387|2
112837|3
116147|2
119244|2
119665|4
122570|2
122628|2
122787|2
123477|2
123569|2
124361|2
125905|2
126096|2
126234|5
127345|4
128824|3
129807|3
129900|2
130003|2
131784|2
131844|5
134758|2
135360|2
136397|2
137150|3
138325|2
138793|2
139652|2
140604|2
140935|3
143712|2
144165|3
146064|2
148649|2
150708|3
151030|2
154673|2
154733|2
154887|2
160099|4
167060|5
168582|2
170005|5
170330|2
170723|2
173102|2
173693|2
173891|3
174698|2
175447|2
176049|3
176054|2
176059|2
176252|2
176929|2
178885|2
178909|2
179399|3
179789|2
180141|2
180514|2
181281|2
181774|2
182518|3
182937|3
183142|7
183957|2
183958|2
184591|2
185500|3
185892|2
186492|2
186644|2
187331|4
187519|2
187889|3
189777|2
190118|4
190689|4
192012|2
192228|2
192341|2
192505|3
192566|2
192616|3
192633|2
192694|2
192742|2
192971|5
193260|2
193486|2
193545|2
193791|2
193902|2
```

**Comment by jhooper04** [comment]
i guess there were duplicate ids. I added the "PRIMARY KEY ON CONFLICT IGNORE"
Should be okay to ignore if there are already duplicates. Hopefully there are not many as to force the db to go back to scanning.

[sban_upgrade_indexes.txt](https://github.com/shivajiva101/sban/files/3547268/sban_upgrade_indexes.txt)

**Comment by jhooper04** [comment]
Should probably dig into the code to figure out why there are duplicates. Could probably squeeze a bit more performance by redesigning the tables.

**Comment by shivajiva101** [comment]
I think you had better take a look at dev branch, it has a better structure, before you go to far. I'm using a field to flag bans as active in the version you are looking at...

**Comment by jhooper04** [comment]
ah, will do. haven't tried redesigning yet, that's def gonna be mod code changes

**Comment by rubenwardy** [comment]
on_joinplayer was taking between 6 and 40 seconds. I've added the following indices, which reduces it to roughly 1 second:

```
CREATE UNIQUE INDEX index_name_name ON name(name);
CREATE INDEX index_name_lastlogin ON name(last_login);
CREATE UNIQUE INDEX index_address_ip ON address(ip);
CREATE INDEX index_address_lastlogin ON address(last_login);
```

Here's my pseudo profiler for ANAND joining from a new IP:

```
Profiling call for player ANAND
[sban:profiler] - init took 0.000 seconds
Sqlite Trace: 			SELECT id
			FROM name
			WHERE name = 'ANAND' LIMIT 1;
[sban:profiler] - get_id took 0.000 seconds
[sban:profiler] - manage_hotlist took 0.000 seconds
[sban:profiler] - trim_cache took 0.000 seconds
[sban:profiler] - id: get_id took 0.000 seconds
Sqlite Trace: 		INSERT INTO violation VALUES (20837,124822,'::ffff:X.Y.Z.A',1567608725)
[sban] INSERT applied to db table violation on rowid 13
[sban:profiler] - id: create_idv_record took 0.313 seconds
Sqlite Trace: 	BEGIN;
Sqlite Trace: UPDATE address
	SET
	violation = 'true'
	WHERE ip = '::ffff:X.Y.Z.A';
[sban] UPDATE applied to db table address on rowid 434128
Sqlite Trace: COMMIT;
[sban:profiler] - id: update_idv_status took 0.497 seconds
Sqlite Trace: 	UPDATE name SET
	last_login = 1567608726,
	login_count = login_count + 1
	WHERE name = 'ANAND';
[sban] UPDATE applied to db table name on rowid 23747
[sban:profiler] - id: update_login took 0.512 seconds
[sban:profiler] - Total time: 1.322 seconds
``
