### ISSUE TITLE
After temp ban ended server crashes

### ISSUE THREAD

**Issue by PiMonkeyServers** [shivajiva101/sban#29]
After temp banning a player for an hour all was well and then the hour ended and about 10 minutes later the server crashed with this error

`2019-11-24 23:17:08: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/minetest/bin/../mods/sban/init.lua:`
`2019-11-24 23:17:08: ERROR[Main]: /home/minetest/minetest/bin/../mods/sban/init.lua:1363: bad argument #8 to 'format' (string expected, got nil)`
`2019-11-24 23:17:08: ERROR[Main]: stack traceback:`
`2019-11-24 23:17:08: ERROR[Main]:       [C]: in function 'format'`
`2019-11-24 23:17:08: ERROR[Main]:       /home/minetest/minetest/bin/../mods/sban/init.lua:1363: in function 'process_expired_bans'`
`2019-11-24 23:17:08: ERROR[Main]:       /home/minetest/minetest/bin/../mods/sban/init.lua:1374: in main chunk`

Server does not start at all now it just gives this error

**Comment by ClobberXD** [comment]
Haven't seen the code, but the error seems to hint at a simple problem.

We haven't ever encountered this crash in CTF, AFAIK.

**Comment by shivajiva101** [comment]
Seems you have a temp ban with no last position for the player, I've altered the code to handle missing last position data for temp bans, presumably this was a temp ban added when the player was offline so there would be no position data to save

**Comment by PiMonkeyServers** [comment]
ty a lot
Yes i temp banned the player while they were offline
Updated the mod and all works so once again thank you

p.s.Nice to see u again btw Shivajiva
-Jhalman from skyblock a long time ago
