### ISSUE TITLE
Time specifiers should be case-insensitive, or give an error

### ISSUE THREAD

**Issue by rubenwardy** [shivajiva101/sban#3]
> cmd tempban PotatoGuy 1000d cheating
> Banned PotatoGuy until Mon 09 Oct 2017 12:55:57 AM UTC.

**Comment by Ezhh** [comment]
How to handle minutes vs. months? 

The usage here was copied from xban2, and I suspect being able to tell those apart was the original reason.

**Comment by rubenwardy** [comment]
well, it should give an error at least

**Comment by shivajiva101** [comment]
Fixed: now accepts lower-case for days, weeks & years. Months remains M
