### ISSUE TITLE
Unban player crashes server

### ISSUE THREAD

**Issue by PiMonkeyServers** [shivajiva101/sban#30]
a staff member perm banned a player and we since decided to unban this player but when I type in /bang and then enter the players name and a unban reason the server crashes when i click unban

with this error

`2020-01-01 15:57:04: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback on_playerReceiveFields(): /home/minetest/minetest/bin/../mods/sban/init.lua:937: bad argument #10 to 'format' (string expected, got nil)`
`2020-01-01 15:57:04: ERROR[Main]: stack traceback:`
`2020-01-01 15:57:04: ERROR[Main]:       [C]: in function 'format'`
`2020-01-01 15:57:04: ERROR[Main]:       /home/minetest/minetest/bin/../mods/sban/init.lua:937: in function 'update_ban_record'`
`2020-01-01 15:57:04: ERROR[Main]:       /home/minetest/minetest/bin/../mods/sban/init.lua:1663: in function '?'`
`2020-01-01 15:57:04: ERROR[Main]:       ...e/minetest/minetest/bin/../builtin/game/register.lua:429: in function <...e/minetest/minetest/bin/../builtin/game/register.lua:413>`

**Comment by shivajiva101** [comment]
Thanks, bug caused by mistakenly using the destination column name, not the actual one used in active bans table
