### ISSUE TITLE
Banning someone doesn't always kick them

### ISSUE THREAD

**Issue by rubenwardy** [shivajiva101/sban#31]
Checking with ban_record shows they were banned, I then kicked them (which worked). This is 5.4.0-dev

There are no applicable log messages:

```
ACTION[Server]: [sban] Joker-_- banned by rubenwardy reason: hacking
ACTION[Server]: rubenwardy kicks Joker-_-    (this was manually done)
[Server]: [CTF | team] Removing player "Joker-_-"
```

Mods are capture the flag + MT-CTF/rules, MT-CTF/servermods, sauth (d2e0aa834c7c0b6d6000af98eb22088b905441c3), sban (44695d22df6c1fdaeac8213092f1b97a6cb3d534)

**Comment by shivajiva101** [comment]
Thanks for the insightful description of the issue. Just a couple of questions:

On what version(s) of MT?
What other mods are installed? 
Can the player be kicked via the chat console when this happens?
Is the player banned subsequently?
Does the log reveal anything?

**Comment by rubenwardy** [comment]
I'm still trying to find information behind this, edited OP

**Comment by LoneWolfHT** [comment]
It's pretty much like the kick command isn't run

**Comment by shivajiva101** [comment]
Yes, in which case I'm trying to pin down the point of failure prior to this point https://github.com/shivajiva101/sban/blob/master/init.lua#L860 and need some clues

If the name_records search fails that point wouldn't be reached, any chance you could check how many name records are attached to that id?

It would be handy to know if that data is intact so it can be ruled out, the ban message proves we hit L854 so it's the next logical step

If the data is intact then it's a timeout from the sql query. It could be restructured for the original identity if the query fails to ensure it steps in and executes the kick regardless of that point of failure

I think that would be a good idea regardless so I'll instigate the changes when I have had some sleep

**Comment by rubenwardy** [comment]
Thanks for the fix :)

**Comment by magnetar47** [comment]
This issue still persists. Same server, same mods. `sban` submodule is at commit 059026b.

**Comment by shivajiva101** [comment]
No clues in the log file?

**Comment by LoneWolfHT** [comment]
Log level at 'action':
```
2022-08-21 10:48:54: ACTION[Server]: [sban] ALLCAPSDUDE temp banned by Kat reason: Excessive use of caps lock
(failed to kick)
2022-08-21 10:49:00: ACTION[Server]: Kat kicks ALLCAPSDUDE
2022-08-21 10:49:00: ACTION[Server]: ALLCAPSDUDE leaves game.
```

I'll set the log level to 'info' and see if it catches anything

**Comment by shivajiva101** [comment]
I've looked at the create ban process and restructured the call to pass the name instead of id into the kicker function so now if db request for records come back empty because it's busy, it defaults to using the name passed in to the function to kick the player, logging a warning about that event so it becomes obvious it caught the point of failure. Update and let me know if you get the log events pls
