### ISSUE TITLE
The bang/GUI crashes the server while showing some players

### ISSUE THREAD

**Issue by hlqkj** [shivajiva101/sban#34]
I am not sure, but trying to diagnose this (see the logged error below) I think that the crash happens when the GUI tries to show a player's record with an 'expires: never' ban (trying the /ban_record command on the same player works fine instead).

```
2021-12-05 14:44:29: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'sauth' in callback on_playerReceiveFields(): /home/minetest/mt/bin/../mods/sban/init.lua:1480: attempt to concatenate a nil value
2021-12-05 14:44:29: ERROR[Main]: stack traceback:
2021-12-05 14:44:29: ERROR[Main]:        /home/minetest/mt/bin/../mods/sban/init.lua:1480: in function 'create_info'
2021-12-05 14:44:29: ERROR[Main]:        /home/minetest/mt/bin/../mods/sban/init.lua:1547: in function 'update_state'
2021-12-05 14:44:29: ERROR[Main]:        /home/minetest/mt/bin/../mods/sban/init.lua:1660: in function 'func'
2021-12-05 14:44:29: ERROR[Main]:        .../minetest/mt/bin/../builtin/profiler/instrumentation.lua:106: in function <.../minetest/mt/bin/../builtin/profiler/instrumentation.lua:100>
2021-12-05 14:44:29: ERROR[Main]:        /home/minetest/mt/bin/../builtin/game/register.lua:425: in function </home/minetest/mt/bin/../builtin/game/register.lua:409>
```

Looking at the error log it seems the `nil` value which is causing the error is `entry.expires` in init.lua line 1480:

https://github.com/shivajiva101/sban/blob/30c882337bf8edf4658198afd7139800341acd4e/init.lua#L1479-L1481

I should mention now that I just updated the mod and the sban.sqlite file according to instructions from README.md, starting from a fairly old situation (Dark Lands). So I went looking in [sban_update.sqlite](https://github.com/shivajiva101/sban/blob/30c882337bf8edf4658198afd7139800341acd4e/tools/sban_update.sql) and noticed that there is indeed a statement to explicitly set the `expires` field to zero where it is `''` (nil).

https://github.com/shivajiva101/sban/blob/30c882337bf8edf4658198afd7139800341acd4e/tools/sban_update.sql#L197-L198

However:

1. the statement only attempts to alter the `active` table while there is no such statement for the `expired` table (from which my error is originating);
2. The `active` table itself is actually not updated, because at that stage the relevant data is in the `active_tmp` table instead but the script updates `active` (which should be empty, data gets inserted into it later).

Does this makes sense or I'm looking at the wrong end of the stick?

EDIT: I think the `type(e.expires) == "number"` check in the chunk below is the reason why /ban_record works instead:

https://github.com/shivajiva101/sban/blob/30c882337bf8edf4658198afd7139800341acd4e/init.lua#L557-L559

**Comment by hlqkj** [comment]
An update: I've been able to solve by manually running the following lines in sqlite3. Perhaps just updating the sban_update.sql could be a trivial fix, for the few like me that still have to run it :)

```sql
UPDATE active SET expires = 0 WHERE expires = '';
UPDATE expired SET expires = 0 WHERE expires = '';
```

**Comment by shivajiva101** [comment]
I appreciate your efforts in tracing the logic, it has been a while since I looked at this code :smile:

**Comment by shivajiva101** [comment]
you might want to update

**Comment by hlqkj** [comment]
Oh you also updated the code! Thanks for notifying me, updated 😊

**Comment by hlqkj** [comment]
Sorry to bother again, and still not sure what the problem is. However, after doing the final upgrade yesterday it seems I have many perma-banned players resulting unbanned instead (Unbanned by: sban_update Reason: ban expired Time: Fri 10 Dec 2021). Will try to get more info as soon as I can!

**Comment by shivajiva101** [comment]
hmm presumably from me 'fixing' this function https://github.com/shivajiva101/sban/blob/master/init.lua#L1415
executed on mod load.

Only thing important here is that it unbanned them when current UTC was greater than the expires value, anything outside of that scope is a bug. The function exists to unload the join event check as much as possible. If you look at the code for prejoin event it clears any temp ban on that player if UTC is greater than expires which would be the only trigger prior to me fixing that function, so temp banned players who failed to login after that expiry would have remained in the table running earlier versions of the mod

I'll do some tests on perma banned see if I can catch anything screwed up but I'm wondering if you are using or have used sban.ban_max in config at any point

UPDATE: running my sban.sqlite from skyblocks results in no perma bans being unbanned, it's  ~60Mb file with over 400 bans in it so it's a reasonably sized data set

**Comment by hlqkj** [comment]
Thanks for your help. I must be doing something wrong then: I tried again to update the old database and I keep getting an empty 'active' table. Some quick `SELECT COUNT(*)` queries done on both the old and updated databases shows that somehow all the bans ended up into the expired table... ~Will try to investigate more tomorrow.~

UPDATE: I couldn't resist doing some more testing now. I removed the drop table statements and run the update one more time: since I see that the 'active_tmp' table gets populated, I'm now suspecting the following lines in sban_update.sql but can't figure it out...

https://github.com/shivajiva101/sban/blob/adb7e3b7e7d637aef00dd72467e06a7013a19cdc/tools/sban_update.sql#L215-L223

**Comment by shivajiva101** [comment]
Ah didn't realise you started at the beginning, okay I'll have a look at that but I'm using `strftime('%s','now')` to get the current UTC timestamp for the comparison, see [here](https://www.sqlite.org/lang_datefunc.html)

**Comment by hlqkj** [comment]
Yeah I had to start again from the beginning. Before I did just a test but, after you applied the fixes I was more confident to re-do the upgrade with your code than my own tweaks: I don't trust myself enough to risk messing up that database :)

Besides, I think I found the problem. The processing of missed expired active entries can't be done like that, because all the active ban records already inserted in the active table, had their `expires` field set to zero by this line:

https://github.com/shivajiva101/sban/blob/adb7e3b7e7d637aef00dd72467e06a7013a19cdc/tools/sban_update.sql#L169-L170

Perhaps, you could add an additional condition in the `WHERE` clause like:
```sql
... WHERE expires != 0 AND expires < strftime('%s', 'now');
```

The `process_expired_bans()` function in init.lua is already safe on this point as it already has a ~= 0 check:
https://github.com/shivajiva101/sban/blob/adb7e3b7e7d637aef00dd72467e06a7013a19cdc/init.lua#L1419

-----------------
UPDATE: I confirm that adding the additional condition `expires != 0` on lines 217 and 233 worked. Out of curiosity, about this:
>  it's ~60Mb file with over 400 bans in it so it's a reasonably sized data set

How come it is so big? This one I am working on (Dark Lands) has over 700 bans and 103600 playersdata records but it's just ~5MB!

**Comment by shivajiva101** [comment]
Yea it is under qualified now expired is set to zero earlier, my bad!
The db is large due to the sheer number of people it has seen, the bans aren't taking the space up it's the names and IP addresses :smirk: around a quarter of a million nicks and 440k different ip addresses. Your DB should increase in size after the update due to the indexes it creates to speed up the queries.

Okay should be fixed now with this commit https://github.com/shivajiva101/sban/commit/ea5e0b26c76b84520fb48e214aef27b253b7962a your assistance is much appreciated!

**Comment by shivajiva101** [comment]
@hlqkj please update, found and fixed another issue with new names on known id's

**Comment by hlqkj** [comment]
Updated. Thanks!
