### ISSUE TITLE
sban unbanned all permanently banned players after update

### ISSUE THREAD

**Issue by LoneWolfHT** [shivajiva101/sban#37]
It didn't unban any tempbanned players. Permabans after the update work fine.

![image](https://user-images.githubusercontent.com/28972859/146656203-69813baf-6406-4111-ab72-3d907e3366db.png)
(Screenshot from before they were re-banned)
#
![image](https://user-images.githubusercontent.com/28972859/146657014-6ca2157c-5e39-4553-b22c-ee81c822a420.png)

**Comment by shivajiva101** [comment]
I believe https://github.com/shivajiva101/sban/commit/ea5e0b26c76b84520fb48e214aef27b253b7962a fixes that issue unless you can show me different

see discussion in https://github.com/shivajiva101/sban/issues/34#issuecomment-991876104

**Comment by LoneWolfHT** [comment]
Hmmm, I think I forgot to copy the latest update file into my worlds folder when I tried to update the db. Thanks!
