### ISSUE TITLE
 GUI: Changing index can lead to incorrect bans

### ISSUE THREAD

**Issue by Ezhh** [shivajiva101/sban#8]
List of players pre-populates  based on those currently online; however players online  might change in the time it takes you to enter a ban reason and click Ban. Because the visible list doesn't update as players join and leave, there is a danger you will ban a player other than the intended one, since the list has, unseen by you, updated and another player is now at that index.

**Comment by shivajiva101** [comment]
fixed by storing and using a snapshot of the hotlist
in commit ef7be3ad63fae768fe5aab97656e2abdfbc73a60
